In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv("train (2).csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
df1=df[['Survived','Pclass','Sex','Age','Fare']]
df1.head().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  5 non-null      int64  
 1   Pclass    5 non-null      int64  
 2   Sex       5 non-null      object 
 3   Age       5 non-null      float64
 4   Fare      5 non-null      float64
dtypes: float64(2), int64(2), object(1)
memory usage: 328.0+ bytes


In [6]:
# filling missing value

df1['Age']=df1['Age'].fillna(value=df1['Age'].mean())

C:\Users\dell\AppData\Local\Temp\ipykernel_7644\3070040088.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Age']=df1['Age'].fillna(value=df1['Age'].mean())


In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   Fare      891 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 34.9+ KB


In [8]:
df1.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [9]:
df1['Sex'].replace(['male','female'],[0,1],inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_7644\432905783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Sex'].replace(['male','female'],[0,1],inplace=True)


In [10]:
df1.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    0  22.0   7.2500
1         1       1    1  38.0  71.2833
2         1       3    1  26.0   7.9250
3         1       1    1  35.0  53.1000
4         0       3    0  35.0   8.0500

In [11]:
x=df1[['Pclass','Sex','Age','Fare']]
y=df1['Survived']

In [25]:
x

Pclass  Sex        Age     Fare
0         3    0  22.000000   7.2500
1         1    1  38.000000  71.2833
2         3    1  26.000000   7.9250
3         1    1  35.000000  53.1000
4         3    0  35.000000   8.0500
..      ...  ...        ...      ...
886       2    0  27.000000  13.0000
887       1    1  19.000000  30.0000
888       3    1  29.699118  23.4500
889       1    0  26.000000  30.0000
890       3    0  32.000000   7.7500

[891 rows x 4 columns]

In [24]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=10)

In [13]:
xtrain.shape

(712, 4)

In [14]:
xtest.shape

(179, 4)

In [15]:
712+179

891

In [16]:
classifer=LogisticRegression()
classifer.fit(xtrain,ytrain)

LogisticRegression()

In [17]:
ypred=classifer.predict(xtest)

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,ypred)

array([[102,  15],
       [ 16,  46]], dtype=int64)

In [19]:
(102+46)/(103+15+16+46)

0.8222222222222222

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [21]:
xtrain

array([[ 8.25233303e-01, -7.53844771e-01, -9.04942306e-02,
        -4.96597757e-01],
       [-3.76333388e-01,  1.32653305e+00, -2.06083596e-01,
        -4.33020011e-01],
       [ 8.25233303e-01,  1.32653305e+00,  1.90926816e-03,
        -3.24167322e-01],
       ...,
       [-1.57790008e+00, -7.53844771e-01,  1.90926816e-03,
         3.67382090e+00],
       [ 8.25233303e-01, -7.53844771e-01, -1.36197725e+00,
        -4.18602861e-01],
       [-3.76333388e-01, -7.53844771e-01,  4.87452598e-01,
        -4.33020011e-01]])

In [22]:
classifer=LogisticRegression()
classifer.fit(xtrain,ytrain)
ypred=classifer.predict(xtest)
confusion_matrix(ytest,ypred)

array([[103,  14],
       [ 16,  46]], dtype=int64)

In [23]:
(103+46)/(103+14+16+46)

0.8324022346368715